apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-theme-diary-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: checkbox
          name: disableDarkmode
          label: 禁用暗黑模式
          value: false
        - $formkit: checkbox
          name: enableLaTeX
          label: 启用 LaTeX 支持
          value: false
