apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-diary
spec:
  displayName: Diary
  version: 1.0.1
  requires: ">=2.0.0"
  author:
    name: amazingrise
    website: https://github.com/amazingrise
  description: A simple and elegant blog theme ported from Hugo
  logo: https://avatars.githubusercontent.com/u/32314537
  website: https://github.com/amazingrise/hugo-theme-diary
  repo: https://github.com/amazingrise/hugo-theme-diary
  license:
    - name: MIT
      url: https://github.com/amazingrise/hugo-theme-diary/blob/main/LICENSE
  settingName: halo-theme-diary-setting
  configMapName: halo-theme-diary-config
